### ISSUE TITLE
IPv4 problem im Rack

### ISSUE THREAD

**Issue by Sec42** [muccc/network#4]
Der iridium-laptop im rack (mitte) ist periodisch (minutenweise) nicht über V4 zu erreichen. 

--- 83.133.179.2 ping statistics ---
3485 packets transmitted, 1737 received, 50% packet loss, time 3542658ms
rtt min/avg/max/mdev = 0.335/6.732/43.831/8.496 ms

Über v6 scheint es keine Probleme zu geben

**Comment by saerdnaer** [comment]
Gefühlt hab ich manchmal ein ähnliches Problem auch aus dem WLAN.

**Comment by saerdnaer** [comment]
Offenbar gibts da eine Kollision bei der IPv4 Adress-Vergabe mit einem Gerät das sich "backup" nennt. Kannst du mir mal die MAC-Adresse des Rechners zukommen lassen.

**Comment by saerdnaer** [comment]
iridium-laptop hat neue IPv4 Adresse bekommen.
